### ISSUE TITLE
returning parameters in W as numpy array

### ISSUE THREAD

**Issue by timnon** [alexeygrigorev/libffm-python#10]
Is it somehow possible to get the parameters in `W` as a numpy array?

I tried
```
m = model._model.m
n = model._model.n
k = model._model.k
W = np.ctypeslib.as_array(model._model.W,(n,m,k))
```
but this clearly didnt work and i am sadly not an expert with python-c interfacing.

**Comment by timnon** [comment]
Seems to work as follows:
```
m = model._model.m
n = model._model.n
k = model._model.k
kALIGN = 8

W = np.ctypeslib.as_array(model._model.W,(1,n*m*kALIGN))[0]
W = W.reshape(n,m,kALIGN)
W = W[:,:,:k]
```
However `kALIGN` is not exposed so far, will write a pull request to include all this.

**Comment by timnon** [comment]
sth is wrong, the formula above only works for small toy examples with `k=1`. I was expecting that `kALIGN` goes up in steps together with `k` (the exact step-size still needs to get reverse-engineered). However, if i try to manually do a prediction using the extracted `W` i get strange results. This is how i run the prediction in python:

```
import itertools

i = 0 #index for which to compute the classification probability
sig = lambda x: 1/(1+np.exp(-x))
pairs = itertools.combinations(X[i],2)
proba = sig(sum( (v0*W[i0,j1]) @ (v1*W[i1,j0]) for (j0,i0,v0), (j1,i1,v1) in pairs ))
print(proba)
```

This works for `k=1` with the following example and `kALIGN=8`, but not anymore with `k=5` for all reasonable `kALIGN` which i tested:

```
X = [[(0, 0, 1),(1, 1, 2),(1,2,-1)],
     [(0, 0, 1),(1, 2, 1),(1,1,-2)]]
Y = [0,1]
```

Also larger examples with `k=1` didnt work, sth must also be wrong with my prediction formula?

**Comment by timnon** [comment]
for the record, i think this works:
```
import itertools
sig = lambda x: 1/(1+np.exp(-x))

m = model._model.m
n = model._model.n
k = model._model.k

# these two new methods need to get externalized
k_aligned = ffm._lib.ffm_get_k_aligned(k)
kALIGN = ffm._lib.ffm_get_kALIGN()

align0 = 2*k_aligned
align1 = m*align0

W = np.ctypeslib.as_array(model._model.W,(1,n*align1))[0]
W = W.reshape((n,m,align0))
I = np.arange(k) + ( np.floor(np.arange(align0)/4).astype(int)*4 )[:k]
W = W[:,:,I]

i = 0 #some sample
pairs = itertools.combinations(X[i],2)
proba = sig(sum( (v0*W[i0,j1]) @ (v1*W[i1,j0]) for (j0,i0,v0), (j1,i1,v1) in pairs ))
print(proba)
```

**Comment by alexeygrigorev** [comment]
Thanks! Feel free to send a PR with the functionality you need

**Comment by timnon** [comment]
in pull request
