### ISSUE TITLE
Train returns NaN with large field values

### ISSUE THREAD

**Issue by QuinRiva** [alexeygrigorev/libffm-python#5]
If I use large values for the field value (field/feature 40), the model predicts nan, although smaller values work fine.

Smaller values:

```
X = [[(0, 0, 1), (1, 18, 1), (40, 40, 32)],
     [(0, 0, 1), (1, 18, 1), (40, 40, 300)],
     [(0, 0, 1), (1, 4, 1), (40, 40, 100)]]

y = [1, 1, 0]

ffm_data = ffm.FFMData(X, y)

model = ffm.FFM(eta=0.205, lam=0.0001, k=4)
model.init_model(ffm_data)
model.iteration(ffm_data)
y_pred = model.predict(ffm_data)
print(y_pred)

[ 0.99700552  1.          0.99695754]
```

However changing the last value from 100 to 200:
```
X = [[(0, 0, 1), (1, 18, 1), (40, 40, 32)],
     [(0, 0, 1), (1, 18, 1), (40, 40, 300)],
     [(0, 0, 1), (1, 4, 1), (40, 40, 200)]]

[ nan  nan  nan]
```

**Comment by alexeygrigorev** [comment]
I believe you should standardize the numerical fields before putting them into any SGD-based algorithm, including FFM. 

You can try e.g. [StandardScaler](http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html) from sklearn
